CREATE DATABASE IF NOT EXISTS tde_db;
CREATE TABLE IF NOT EXISTS `tde_db`.`cliente` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `senha` VARCHAR(45) NOT NULL,
  `confirmar_senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `tde_db`.`administrador` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8; 

CREATE TABLE IF NOT EXISTS `tde_db`.`produto` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `preco` DOUBLE(10,2) NOT NULL,
  `imagem` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `tde_db`.`carrinho` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `preco_unitario` DOUBLE(10,2) NOT NULL,
  `preco_total` DOUBLE(30,2) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `imagem` VARCHAR(100) NOT NULL,
  `id_produto` INT(10) UNSIGNED  NOT NULL,
  `id_cliente` INT(10) UNSIGNED  NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_produto`) REFERENCES `tde_db`.`produto`(`id`)  ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;